---
version: '3'
services:
  exporter:
    image: prom/node-exporter
    command: --collector.textfile.directory=/textfiles
    volumes:
      # - ~/Library/Application Support/factorio/script-output/graftorio-ng/:/textfiles # macOS
      # - ${APPDATA}\Factorio\script-output\graftorio-ng:/textfiles # Windows
      - ~/bin/factorio/script-output/graftorio-ng:/textfiles # Linux
    ports:
      - 9100
  prometheus:
    image: prom/prometheus
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - 3000:3000
